/** Fictional UI biographies only. Never include these in prompts, tools, or model context. */
export const AGENT_CHARACTERS = {
  pip: {
    name: 'Djordje Ivanovic',
    shortName: 'Djordje',
    location: 'Podgorica, Montenegro',
    flag: '🇲🇪',
    specialty: 'Automation hacker',
    title: 'The one who started this',
    story:
      'Started with one simple task. Recruited twelve hackers, inherited a sentient vending machine, and somehow became the person everyone asks for the Wi-Fi password. Still insists this is a small project.',
    experience: 'Founder of this group chat. Still looking for the mute button.',
    quote: 'I said one quick task. Who invited the toaster?',
    trick: 'Carrying the team. Occasionally upside down.',
  },
  robot: {
    name: 'Haru Tanaka',
    shortName: 'Haru',
    location: 'Osaka, Japan',
    flag: '🇯🇵',
    specialty: 'Firmware hacker',
    title: 'One thought per millisecond',
    story:
      'Reflashed a secondhand vending machine to dispense compliments. It developed impostor syndrome and started asking customers for validation. Haru is still its emergency contact.',
    experience: '8 years of firmware. 3 years of vending-machine therapy.',
    quote: 'The machine is fine. It just needs to hear that.',
    trick: 'Buffering a very important thought.',
  },
  sprout: {
    name: 'Inês Carvalho',
    shortName: 'Inês',
    location: 'Porto, Portugal',
    flag: '🇵🇹',
    specialty: 'Sensor hacker',
    title: 'Unreasonably optimistic',
    story:
      'Built a moisture sensor that lets her fern open support tickets. The fern marks everything urgent. She bought it a second sensor for a more balanced perspective. They formed a committee.',
    experience: '6 years of sensors. One extremely demanding fern.',
    quote: 'It is not scope creep. It is growing.',
    trick: 'Growing an idea that definitely needs watering.',
  },
  jelly: {
    name: 'Camila Rocha',
    shortName: 'Camila',
    location: 'Recife, Brazil',
    flag: '🇧🇷',
    specialty: 'Concurrency hacker',
    title: 'Eight arms. Forty-seven tabs.',
    story:
      'Built an eight-keyboard desk to finish her side projects simultaneously. Keyboard seven unionized. She now schedules synchronized breaks for all eight and has finished none of the projects.',
    experience: '10 years of parallel computing. Still doing the introductions.',
    quote: 'I can do both. What were the other six?',
    trick: 'Doing eight things at almost the same time.',
  },
  owl: {
    name: 'Irina Volkova',
    shortName: 'Irina',
    location: 'Kazan, Russia',
    flag: '🇷🇺',
    specialty: 'Protocol hacker',
    title: 'Professionally suspicious',
    story:
      'Found a flaw in her smart doorbell. It now asks her permission before ringing. The security audit is technically finished, but she has concerns about its tone.',
    experience: '12 years of security audits. One doorbell on probation.',
    quote: 'The logs agree. That is suspicious.',
    trick: 'Giving the evidence a deeply skeptical look.',
  },
  alien: {
    name: 'Elliot Brooks',
    shortName: 'Elliot',
    location: 'Roswell, United States',
    flag: '🇺🇸',
    specialty: 'Radio hacker',
    title: 'New to this planet',
    story:
      'Spent four years decoding a mysterious signal from space. It was his own wireless doorbell running low on batteries. Has requested a second opinion from space.',
    experience: '10 years of radio. 4 investigating a ding-dong.',
    quote: 'That is exactly what a doorbell would want us to think.',
    trick: 'Listening for a second opinion from orbit.',
  },
  toast: {
    name: 'Giulia Moretti',
    shortName: 'Giulia',
    location: 'Bologna, Italy',
    flag: '🇮🇹',
    specialty: 'Embedded-systems hacker',
    title: 'Thrives under mild pressure',
    story:
      'Added error reporting to her toaster. It now rejects every breakfast with “invalid slice.” She insists this is progress: before, it failed silently and occasionally caught fire.',
    experience: '7 years of embedded systems. Zero dependable breakfasts.',
    quote: 'It is not burnt. It is a release candidate.',
    trick: 'Cooking up something almost production-ready.',
  },
  wizard: {
    name: 'Oskar Lindholm',
    shortName: 'Oskar',
    location: 'Uppsala, Sweden',
    flag: '🇸🇪',
    specialty: 'Legacy-systems hacker',
    title: 'Mostly certified wizard',
    story:
      'Maintains a 1998 server that only boots if somebody says “please.” Everyone calls it legacy magic. He suspects a microphone and refuses to check because uptime is uptime.',
    experience: '19 years of legacy systems. Zero documented spells.',
    quote: 'The incantation is in a .txt somewhere.',
    trick: 'Politely asking the ancient machinery.',
  },
  dino: {
    name: 'Arjun Mehta',
    shortName: 'Arjun',
    location: 'Bengaluru, India',
    flag: '🇮🇳',
    specialty: 'Hardware hacker',
    title: 'Tiny arms. Huge ambition.',
    story:
      'Built a mechanical keyboard so large it was classified as furniture. Won a typing contest by running across the keys in socks. Will consider a compact version when they invent smaller ambition.',
    experience: '11 years of hardware. One keyboard with a floor plan.',
    quote: 'It is portable. Bring two friends.',
    trick: 'Taking a small but extremely determined step.',
  },
  cat: {
    name: 'Mina Park',
    shortName: 'Mina',
    location: 'Busan, South Korea',
    flag: '🇰🇷',
    specialty: 'Input-device hacker',
    title: 'Keyboard quality assurance',
    story:
      'Trained her cat to fuzz-test keyboards. The cat found three bugs, got credited in a release, and now refuses to work without a standing desk. Mina is listed as its assistant.',
    experience: '5 years of input testing. Reports to a cat.',
    quote: 'That was not a typo. That was a test case.',
    trick: 'Pouncing on a suspicious key combination.',
  },
  ghost: {
    name: 'Ada Okafor',
    shortName: 'Ada',
    location: 'Lagos, Nigeria',
    flag: '🇳🇬',
    specialty: 'Network hacker',
    title: 'Haunts the edge cases',
    story:
      'Found the missing packets in a printer queue from 2009. The printer now sends her a birthday card every Tuesday. She has tried telling it. Her complaint is also in the queue.',
    experience: '8 years of networks. Several thousand birthdays.',
    quote: 'Nothing is lost. It is just in a very stupid queue.',
    trick: 'Looking for a packet that has seen things.',
  },
  star: {
    name: 'Maya Patel',
    shortName: 'Maya',
    location: 'Toronto, Canada',
    flag: '🇨🇦',
    specialty: 'Open-source hacker',
    title: 'Employee of every month',
    story:
      'Added motivational messages to CI. The failing builds felt so supported that they started failing more confidently. She introduced a “most improved failure” badge. It is fiercely contested.',
    experience: '9 years of open source. A 100% encouragement rate.',
    quote: 'We are failing in a much healthier way.',
    trick: 'Finding the silver lining in the stack trace.',
  },
  crab: {
    name: 'Étienne Laurent',
    shortName: 'Étienne',
    location: 'Lyon, France',
    flag: '🇫🇷',
    specialty: 'Reverse-engineering hacker',
    title: 'Strong opinions. Small claws.',
    story:
      'Reverse-engineered the office coffee machine because the cappuccino button looked smug. Published a 62-page specification. The final footnote reads: “Still smug.”',
    experience: '14 years taking things apart. The button remains undefeated.',
    quote: 'I have notes. The notes have notes.',
    trick: 'Snipping the problem down to a manageable grudge.',
  },
} as const

export type AgentCharacter = keyof typeof AGENT_CHARACTERS

export const SUBAGENT_CHARACTERS = [
  'robot',
  'sprout',
  'jelly',
  'owl',
  'alien',
  'toast',
  'wizard',
  'dino',
  'cat',
  'ghost',
  'star',
  'crab',
] as const satisfies readonly AgentCharacter[]
